import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      // Generated by `npm run desktop:stage`: a bundled copy of code that is
      // already linted at its source.
      'apps/desktop/build/**',
      // Installers produced by electron-builder.
      'apps/desktop/release/**',
      '**/node_modules/**',
      '**/coverage/**',
      '**/*.config.{js,ts}',
      'assets/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
    },
  },
  {
    files: ['apps/desktop/**/*.mjs', 'scripts/**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { process: 'readonly', console: 'readonly' },
    },
  },
);
