import type { NamePool, WorldGenerationConfig } from '@football-life/shared';

const italy: NamePool = {
  firstNames: [
    'Marco',
    'Luca',
    'Matteo',
    'Andrea',
    'Davide',
    'Simone',
    'Francesco',
    'Alessandro',
    'Lorenzo',
    'Giuseppe',
    'Antonio',
    'Federico',
    'Riccardo',
    'Stefano',
  ],
  lastNames: [
    'Rossi',
    'Bianchi',
    'Esposito',
    'Romano',
    'Colombo',
    'Ricci',
    'Marino',
    'Greco',
    'Bruno',
    'Gallo',
    'Conti',
    'De Luca',
    'Costa',
    'Giordano',
  ],
  cities: [
    'Milano',
    'Torino',
    'Roma',
    'Napoli',
    'Firenze',
    'Bologna',
    'Genova',
    'Verona',
    'Palermo',
    'Bari',
    'Cagliari',
    'Parma',
    'Udine',
    'Lecce',
    'Sassuolo',
    'Empoli',
  ],
};

const england: NamePool = {
  firstNames: [
    'Jack',
    'Harry',
    'Oliver',
    'George',
    'James',
    'William',
    'Thomas',
    'Charlie',
    'Daniel',
    'Ryan',
    'Lewis',
    'Connor',
    'Callum',
    'Mason',
  ],
  lastNames: [
    'Smith',
    'Jones',
    'Taylor',
    'Brown',
    'Wilson',
    'Evans',
    'Walker',
    'Wright',
    'Roberts',
    'Green',
    'Hall',
    'Wood',
    'Clarke',
    'Carter',
  ],
  cities: [
    'London',
    'Manchester',
    'Liverpool',
    'Leeds',
    'Newcastle',
    'Birmingham',
    'Brighton',
    'Nottingham',
    'Sheffield',
    'Leicester',
    'Southampton',
    'Norwich',
    'Burnley',
    'Wolverhampton',
    'Watford',
    'Sunderland',
  ],
};

const spain: NamePool = {
  firstNames: [
    'Sergio',
    'Carlos',
    'Javier',
    'Pablo',
    'Alvaro',
    'Marcos',
    'Diego',
    'Raul',
    'Adrian',
    'Hugo',
    'Mario',
    'Iker',
    'Daniel',
    'Fernando',
  ],
  lastNames: [
    'Garcia',
    'Martinez',
    'Lopez',
    'Sanchez',
    'Gonzalez',
    'Rodriguez',
    'Fernandez',
    'Perez',
    'Gomez',
    'Ruiz',
    'Diaz',
    'Moreno',
    'Torres',
    'Navarro',
  ],
  cities: [
    'Madrid',
    'Barcelona',
    'Sevilla',
    'Valencia',
    'Bilbao',
    'Vigo',
    'Granada',
    'Villarreal',
    'Getafe',
    'Cadiz',
    'Girona',
    'Osasuna',
    'Mallorca',
    'Elche',
    'Alaves',
    'Levante',
  ],
};

const france: NamePool = {
  firstNames: [
    'Hugo',
    'Lucas',
    'Nathan',
    'Theo',
    'Enzo',
    'Louis',
    'Gabriel',
    'Jules',
    'Clement',
    'Antoine',
    'Maxime',
    'Romain',
    'Yanis',
    'Adrien',
  ],
  lastNames: [
    'Martin',
    'Bernard',
    'Dubois',
    'Thomas',
    'Robert',
    'Richard',
    'Petit',
    'Durand',
    'Leroy',
    'Moreau',
    'Simon',
    'Laurent',
    'Lefebvre',
    'Girard',
  ],
  cities: [
    'Paris',
    'Marseille',
    'Lyon',
    'Lille',
    'Monaco',
    'Nice',
    'Rennes',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Lens',
    'Brest',
    'Reims',
    'Toulouse',
    'Angers',
    'Metz',
  ],
};

const usa: NamePool = {
  firstNames: [
    'Michael',
    'Christopher',
    'Joshua',
    'Tyler',
    'Brandon',
    'Justin',
    'Brian',
    'Kevin',
    'Jason',
    'Aaron',
    'Eric',
    'Adam',
    'Nathan',
    'Caleb',
  ],
  lastNames: [
    'Johnson',
    'Williams',
    'Miller',
    'Davis',
    'Garcia',
    'Rodriguez',
    'Martinez',
    'Anderson',
    'Taylor',
    'Thomas',
    'Moore',
    'Jackson',
    'Martin',
    'Lee',
  ],
  cities: [
    'Atlanta',
    'Seattle',
    'Portland',
    'Orlando',
    'Austin',
    'Nashville',
    'Cincinnati',
    'Columbus',
    'Charlotte',
    'Dallas',
    'Houston',
    'Denver',
    'Chicago',
    'Miami',
    'Boston',
    'Minnesota',
  ],
};

/** Default, fully-validated procedural generation parameters for the MVP. */
export const DEFAULT_WORLD_CONFIG: WorldGenerationConfig = {
  seasonStart: '2024-08-17',
  seasonLengthDays: 300,
  clubsPerTopDivision: 12,
  clubsPerSecondDivision: 12,
  rosterSize: 22,
  age: { min: 16, max: 36, mean: 24, spread: 4 },
  ability: {
    topDivisionMean: 62,
    divisionStep: 12,
    spread: 9,
    min: 20,
    max: 95,
  },
  reputation: { topDivision: 3000, secondDivision: 1200, youth: 400 },
  namePools: {
    IT: italy,
    EN: england,
    ES: spain,
    FR: france,
    US: usa,
  },
};
