import type { NamePool, WorldGenerationConfig } from '@football-life/shared';

const italy: NamePool = {
  firstNames: [
    'Marco',
    'Luca',
    'Matteo',
    'Andrea',
    'Davide',
    'Simone',
    'Francesco',
    'Alessandro',
    'Lorenzo',
    'Giuseppe',
    'Antonio',
    'Federico',
    'Riccardo',
    'Stefano',
  ],
  lastNames: [
    'Rossi',
    'Bianchi',
    'Esposito',
    'Romano',
    'Colombo',
    'Ricci',
    'Marino',
    'Greco',
    'Bruno',
    'Gallo',
    'Conti',
    'De Luca',
    'Costa',
    'Giordano',
  ],
  cities: [
    'Milano',
    'Torino',
    'Roma',
    'Napoli',
    'Firenze',
    'Bologna',
    'Genova',
    'Verona',
    'Palermo',
    'Bari',
    'Cagliari',
    'Parma',
    'Udine',
    'Lecce',
    'Sassuolo',
    'Empoli',
  ],
  // Invented clubs built from a real city and a real footballing nickname —
  // recognisable at a glance, registered to nobody. The first entry is always
  // present in the top division (user request: the Milan side in black and
  // blue never misses a season).
  featuredClubs: [
    'Milano Nerazzurra',
    'Milano Rossonera',
    'Torino Bianconera',
    'Napoli Azzurra',
    'Roma Giallorossa',
    'Roma Biancoceleste',
    'Bergamo Orobica',
    'Firenze Viola',
    'Bologna Felsinea',
    'Como Lariana',
    'Torino Granata',
    'Genova Grifone',
  ],
  secondDivisionClubs: [
    'Palermo Rosanero',
    'Genova Blucerchiata',
    'Bari Biancorossa',
    'Spezia Aquilotti',
    'Cesena Romagnola',
    'Modena Canarina',
    'Venezia Lagunare',
    'Empoli Toscana',
    'Monza Brianzola',
    'Padova Patavina',
    'Pescara Adriatica',
    'Avellino Irpina',
  ],
};

const england: NamePool = {
  firstNames: [
    'Jack',
    'Harry',
    'Oliver',
    'George',
    'James',
    'William',
    'Thomas',
    'Charlie',
    'Daniel',
    'Ryan',
    'Lewis',
    'Connor',
    'Callum',
    'Mason',
  ],
  lastNames: [
    'Smith',
    'Jones',
    'Taylor',
    'Brown',
    'Wilson',
    'Evans',
    'Walker',
    'Wright',
    'Roberts',
    'Green',
    'Hall',
    'Wood',
    'Clarke',
    'Carter',
  ],
  cities: [
    'London',
    'Manchester',
    'Liverpool',
    'Leeds',
    'Newcastle',
    'Birmingham',
    'Brighton',
    'Nottingham',
    'Sheffield',
    'Leicester',
    'Southampton',
    'Norwich',
    'Burnley',
    'Wolverhampton',
    'Watford',
    'Sunderland',
  ],
  featuredClubs: [
    'Manchester Sky Blues',
    'Manchester Red Devils',
    'Merseyside Reds',
    'North London Gunners',
    'West London Blues',
    'North London Lilywhites',
    'Tyneside Magpies',
    'Birmingham Villans',
    'Merseyside Toffees',
    'East London Hammers',
    'Brighton Seagulls',
    'Nottingham Foresters',
  ],
  secondDivisionClubs: [
    'Leicester Foxes',
    'Southampton Saints',
    'Ipswich Tractor Boys',
    'Birmingham Blues',
    'Wrexham Dragons',
    'Norwich Canaries',
    'Teesside Boro',
    'Coventry Elephants',
    'Watford Hornets',
    'Sheffield Blades',
    'Sheffield Owls',
    'Black Country Baggies',
  ],
};

const spain: NamePool = {
  firstNames: [
    'Sergio',
    'Carlos',
    'Javier',
    'Pablo',
    'Alvaro',
    'Marcos',
    'Diego',
    'Raul',
    'Adrian',
    'Hugo',
    'Mario',
    'Iker',
    'Daniel',
    'Fernando',
  ],
  lastNames: [
    'Garcia',
    'Martinez',
    'Lopez',
    'Sanchez',
    'Gonzalez',
    'Rodriguez',
    'Fernandez',
    'Perez',
    'Gomez',
    'Ruiz',
    'Diaz',
    'Moreno',
    'Torres',
    'Navarro',
  ],
  cities: [
    'Madrid',
    'Barcelona',
    'Sevilla',
    'Valencia',
    'Bilbao',
    'Vigo',
    'Granada',
    'Villarreal',
    'Getafe',
    'Cadiz',
    'Girona',
    'Osasuna',
    'Mallorca',
    'Elche',
    'Alaves',
    'Levante',
  ],
  featuredClubs: [
    'Madrid Blanco',
    'Barcellona Blaugrana',
    'Madrid Colchonero',
    'Bilbao Leones',
    'Villarreal Submarino',
    'San Sebastián Donostiarra',
    'Siviglia Verdiblanca',
    'Siviglia Nervionense',
    'Valencia Ches',
    'Vigo Celeste',
    'Pamplona Rojilla',
    'Getafe Azulón',
  ],
  secondDivisionClubs: [
    'La Coruña Herculina',
    'Gijón Rojiblanca',
    'Santander Cántabra',
    'Saragozza Maña',
    'Las Palmas Amarilla',
    'Cadice Gaditana',
    'Granada Nazarí',
    'Eibar Armera',
    'Almería Indálica',
    'Valladolid Pucelana',
    'Málaga Boquerona',
    'Leganés Pepinera',
  ],
};

const france: NamePool = {
  firstNames: [
    'Hugo',
    'Lucas',
    'Nathan',
    'Theo',
    'Enzo',
    'Louis',
    'Gabriel',
    'Jules',
    'Clement',
    'Antoine',
    'Maxime',
    'Romain',
    'Yanis',
    'Adrien',
  ],
  lastNames: [
    'Martin',
    'Bernard',
    'Dubois',
    'Thomas',
    'Robert',
    'Richard',
    'Petit',
    'Durand',
    'Leroy',
    'Moreau',
    'Simon',
    'Laurent',
    'Lefebvre',
    'Girard',
  ],
  cities: [
    'Paris',
    'Marseille',
    'Lyon',
    'Lille',
    'Monaco',
    'Nice',
    'Rennes',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Lens',
    'Brest',
    'Reims',
    'Toulouse',
    'Angers',
    'Metz',
  ],
  featuredClubs: [
    'Parigi Capitale',
    'Marsiglia Olimpica',
    'Lione Rodano',
    'Principato Monaco',
    'Lilla Fiandre',
    'Nizza Costa Azzurra',
    'Lens Minatori',
    'Rennes Bretagna',
    'Strasburgo Alsazia',
    'Tolosa Garonna',
    'Nantes Loira',
    'Brest Finistère',
  ],
  secondDivisionClubs: [
    'Saint-Étienne Verde',
    'Montpellier Linguadoca',
    'Reims Champagne',
    'Troyes Aube',
    'Bastia Corsa',
    'Grenoble Alpi',
    'Amiens Piccardia',
    'Guingamp Armor',
    'Annecy Savoia',
    'Pau Bearn',
    'Laval Mayenne',
    'Le Mans Sarthe',
  ],
};

const germany: NamePool = {
  firstNames: [
    'Lukas',
    'Leon',
    'Finn',
    'Jonas',
    'Felix',
    'Maximilian',
    'Paul',
    'Elias',
    'Niklas',
    'Tim',
    'Moritz',
    'Julian',
    'Florian',
    'Kai',
  ],
  lastNames: [
    'Müller',
    'Schmidt',
    'Schneider',
    'Fischer',
    'Weber',
    'Wagner',
    'Becker',
    'Hofmann',
    'Schäfer',
    'Koch',
    'Bauer',
    'Richter',
    'Klein',
    'Wolf',
  ],
  cities: [
    'Monaco',
    'Dortmund',
    'Lipsia',
    'Berlino',
    'Amburgo',
    'Colonia',
    'Francoforte',
    'Stoccarda',
    'Brema',
    'Hannover',
    'Norimberga',
    'Gelsenkirchen',
    'Leverkusen',
    'Friburgo',
    'Augusta',
    'Mönchengladbach',
  ],
  featuredClubs: [
    'Monaco Baviera',
    'Dortmund Giallonera',
    'Leverkusen Renania',
    'Lipsia Sassonia',
    'Francoforte Meno',
    'Stoccarda Svevia',
    'Friburgo Brisgovia',
    'Brema Anseatica',
    'Wolfsburg Lupi',
    'Mönchengladbach Puledri',
    'Berlino Ferrea',
    'Amburgo Elba',
  ],
  secondDivisionClubs: [
    'Gelsenkirchen Minatori',
    'Berlino Biancoblù',
    'Hannover Rossa',
    'Kaiserslautern Diavoli',
    'Düsseldorf Renana',
    'Norimberga Franconia',
    'Paderborn Vestfalia',
    'Karlsruhe Baden',
    'Magdeburgo Ottoniana',
    'Darmstadt Assia',
    'Bochum Ruhr',
    'Kiel Baltica',
  ],
};

/** Default, fully-validated procedural generation parameters for the MVP. */
export const DEFAULT_WORLD_CONFIG: WorldGenerationConfig = {
  seasonStart: '2024-08-17',
  seasonLengthDays: 300,
  clubsPerTopDivision: 12,
  clubsPerSecondDivision: 12,
  rosterSize: 22,
  age: { min: 16, max: 36, mean: 24, spread: 4 },
  ability: {
    topDivisionMean: 62,
    divisionStep: 12,
    spread: 9,
    min: 20,
    max: 95,
  },
  reputation: { topDivision: 3000, secondDivision: 1200, youth: 400 },
  namePools: {
    IT: italy,
    EN: england,
    ES: spain,
    FR: france,
    DE: germany,
  },
};
