import type { NamePool, WorldGenerationConfig } from '@football-life/shared';

const italy: NamePool = {
  firstNames: [
    'Marco',
    'Luca',
    'Matteo',
    'Andrea',
    'Davide',
    'Simone',
    'Francesco',
    'Alessandro',
    'Lorenzo',
    'Giuseppe',
    'Antonio',
    'Federico',
    'Riccardo',
    'Stefano',
  ],
  lastNames: [
    'Rossi',
    'Bianchi',
    'Esposito',
    'Romano',
    'Colombo',
    'Ricci',
    'Marino',
    'Greco',
    'Bruno',
    'Gallo',
    'Conti',
    'De Luca',
    'Costa',
    'Giordano',
  ],
  cities: [
    'Milano',
    'Torino',
    'Roma',
    'Napoli',
    'Firenze',
    'Bologna',
    'Genova',
    'Verona',
    'Palermo',
    'Bari',
    'Cagliari',
    'Parma',
    'Udine',
    'Lecce',
    'Sassuolo',
    'Empoli',
    'Salerno',
    'Frosinone',
    'Catania',
    'Ancona',
    'Brescia',
    'Vicenza',
  ],
  // Invented clubs built from a real city and a real footballing nickname —
  // recognisable at a glance, registered to nobody. The first entry is always
  // present in the top division (user request: the Milan side in black and
  // blue never misses a season).
  featuredClubs: [
    'Milano Nerazzurra',
    'Milano Rossonera',
    'Torino Bianconera',
    'Napoli Azzurra',
    'Roma Giallorossa',
    'Roma Biancoceleste',
    'Bergamo Orobica',
    'Firenze Viola',
    'Bologna Felsinea',
    'Como Lariana',
    'Torino Granata',
    'Genova Grifone',
    'Udine Friulana',
    'Verona Scaligera',
    'Cagliari Sarda',
    'Parma Ducale',
    'Lecce Salentina',
    'Sassuolo Neroverde',
    'Salerno Ippocampo',
    'Frosinone Ciociara',
  ],
  secondDivisionClubs: [
    'Palermo Rosanero',
    'Genova Blucerchiata',
    'Bari Biancorossa',
    'Spezia Aquilotti',
    'Cesena Romagnola',
    'Modena Canarina',
    'Venezia Lagunare',
    'Empoli Toscana',
    'Monza Brianzola',
    'Padova Patavina',
    'Pescara Adriatica',
    'Avellino Irpina',
    'Catania Etnea',
    'Ancona Dorica',
    'Terni Rossoverde',
    'Brescia Rondinella',
    'Vicenza Berica',
    'Livorno Labronica',
    'Cremona Grigiorossa',
    'Trieste Alabardata',
  ],
};

const england: NamePool = {
  firstNames: [
    'Jack',
    'Harry',
    'Oliver',
    'George',
    'James',
    'William',
    'Thomas',
    'Charlie',
    'Daniel',
    'Ryan',
    'Lewis',
    'Connor',
    'Callum',
    'Mason',
  ],
  lastNames: [
    'Smith',
    'Jones',
    'Taylor',
    'Brown',
    'Wilson',
    'Evans',
    'Walker',
    'Wright',
    'Roberts',
    'Green',
    'Hall',
    'Wood',
    'Clarke',
    'Carter',
  ],
  cities: [
    'London',
    'Manchester',
    'Liverpool',
    'Leeds',
    'Newcastle',
    'Birmingham',
    'Brighton',
    'Nottingham',
    'Sheffield',
    'Leicester',
    'Southampton',
    'Norwich',
    'Burnley',
    'Wolverhampton',
    'Watford',
    'Sunderland',
    'Bournemouth',
    'Luton',
    'Blackburn',
    'Derby',
    'Stoke',
    'Hull',
  ],
  featuredClubs: [
    'Manchester Sky Blues',
    'Manchester Red Devils',
    'Merseyside Reds',
    'North London Gunners',
    'West London Blues',
    'North London Lilywhites',
    'Tyneside Magpies',
    'Birmingham Villans',
    'Merseyside Toffees',
    'East London Hammers',
    'Brighton Seagulls',
    'Nottingham Foresters',
    'West London Cottagers',
    'Black Country Wolves',
    'Bournemouth Cherries',
    'Yorkshire Whites',
    'South London Eagles',
    'Burnley Clarets',
    'Luton Hatters',
    'Blackburn Riversiders',
  ],
  secondDivisionClubs: [
    'Leicester Foxes',
    'Southampton Saints',
    'Ipswich Tractor Boys',
    'Birmingham Blues',
    'Wrexham Dragons',
    'Norwich Canaries',
    'Teesside Boro',
    'Coventry Elephants',
    'Watford Hornets',
    'Sheffield Blades',
    'Sheffield Owls',
    'Black Country Baggies',
    'Derby Rams',
    'Stoke Potters',
    'Hull Tigers',
    'Bristol Robins',
    'Cardiff Bluebirds',
    'Swansea Swans',
    'Portsmouth Pompey',
    'Blackpool Tangerines',
  ],
};

const spain: NamePool = {
  firstNames: [
    'Sergio',
    'Carlos',
    'Javier',
    'Pablo',
    'Alvaro',
    'Marcos',
    'Diego',
    'Raul',
    'Adrian',
    'Hugo',
    'Mario',
    'Iker',
    'Daniel',
    'Fernando',
  ],
  lastNames: [
    'Garcia',
    'Martinez',
    'Lopez',
    'Sanchez',
    'Gonzalez',
    'Rodriguez',
    'Fernandez',
    'Perez',
    'Gomez',
    'Ruiz',
    'Diaz',
    'Moreno',
    'Torres',
    'Navarro',
  ],
  cities: [
    'Madrid',
    'Barcelona',
    'Sevilla',
    'Valencia',
    'Bilbao',
    'Vigo',
    'Granada',
    'Villarreal',
    'Getafe',
    'Cadiz',
    'Girona',
    'Osasuna',
    'Mallorca',
    'Elche',
    'Alaves',
    'Levante',
    'Oviedo',
    'Salamanca',
    'Burgos',
    'Albacete',
    'Murcia',
    'Tenerife',
  ],
  featuredClubs: [
    'Madrid Blanco',
    'Barcellona Blaugrana',
    'Madrid Colchonero',
    'Bilbao Leones',
    'Villarreal Submarino',
    'San Sebastián Donostiarra',
    'Siviglia Verdiblanca',
    'Siviglia Nervionense',
    'Valencia Ches',
    'Vigo Celeste',
    'Pamplona Rojilla',
    'Getafe Azulón',
    'Maiorca Baleare',
    'Elche Franjiverde',
    'Girona Gerundense',
    'Vitoria Babazorra',
    'Vallecas Franjirroja',
    'Huesca Altoaragonesa',
    'Tenerife Chicharrera',
    'Murcia Pimentonera',
  ],
  secondDivisionClubs: [
    'La Coruña Herculina',
    'Gijón Rojiblanca',
    'Santander Cántabra',
    'Saragozza Maña',
    'Las Palmas Amarilla',
    'Cadice Gaditana',
    'Granada Nazarí',
    'Eibar Armera',
    'Almería Indálica',
    'Valladolid Pucelana',
    'Málaga Boquerona',
    'Leganés Pepinera',
    'Oviedo Carbayona',
    'Salamanca Charra',
    'Burgos Castellana',
    'Albacete Manchega',
    'Castellón Orellut',
    'Ferrol Naval',
    'Alcorcón Alfarera',
    'Sabadell Arlecchina',
  ],
};

const france: NamePool = {
  firstNames: [
    'Hugo',
    'Lucas',
    'Nathan',
    'Theo',
    'Enzo',
    'Louis',
    'Gabriel',
    'Jules',
    'Clement',
    'Antoine',
    'Maxime',
    'Romain',
    'Yanis',
    'Adrien',
  ],
  lastNames: [
    'Martin',
    'Bernard',
    'Dubois',
    'Thomas',
    'Robert',
    'Richard',
    'Petit',
    'Durand',
    'Leroy',
    'Moreau',
    'Simon',
    'Laurent',
    'Lefebvre',
    'Girard',
  ],
  cities: [
    'Paris',
    'Marseille',
    'Lyon',
    'Lille',
    'Monaco',
    'Nice',
    'Rennes',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Lens',
    'Brest',
    'Reims',
    'Toulouse',
    'Angers',
    'Metz',
    'Bordeaux',
    'Le Havre',
    'Auxerre',
    'Caen',
    'Nimes',
    'Ajaccio',
  ],
  featuredClubs: [
    'Parigi Capitale',
    'Marsiglia Olimpica',
    'Lione Rodano',
    'Principato Monaco',
    'Lilla Fiandre',
    'Nizza Costa Azzurra',
    'Lens Minatori',
    'Rennes Bretagna',
    'Strasburgo Alsazia',
    'Tolosa Garonna',
    'Nantes Loira',
    'Brest Finistère',
    'Bordeaux Girondina',
    'Le Havre Normanna',
    'Auxerre Borgogna',
    'Angers Angioina',
    'Metz Lorena',
    'Clermont Alvernia',
    'Lorient Merluzzi',
    'Nancy Stanislao',
  ],
  secondDivisionClubs: [
    'Saint-Étienne Verde',
    'Montpellier Linguadoca',
    'Reims Champagne',
    'Troyes Aube',
    'Bastia Corsa',
    'Grenoble Alpi',
    'Amiens Piccardia',
    'Guingamp Armor',
    'Annecy Savoia',
    'Pau Bearn',
    'Laval Mayenne',
    'Le Mans Sarthe',
    'Caen Calvados',
    'Valenciennes Hainaut',
    'Nîmes Crocodili',
    'Ajaccio Imperiale',
    'Sochaux Leoncelli',
    'Rodez Aveyron',
    'Dunkerque Marittima',
    'Bourg Bressana',
  ],
};

const germany: NamePool = {
  firstNames: [
    'Lukas',
    'Leon',
    'Finn',
    'Jonas',
    'Felix',
    'Maximilian',
    'Paul',
    'Elias',
    'Niklas',
    'Tim',
    'Moritz',
    'Julian',
    'Florian',
    'Kai',
  ],
  lastNames: [
    'Müller',
    'Schmidt',
    'Schneider',
    'Fischer',
    'Weber',
    'Wagner',
    'Becker',
    'Hofmann',
    'Schäfer',
    'Koch',
    'Bauer',
    'Richter',
    'Klein',
    'Wolf',
  ],
  cities: [
    'Monaco',
    'Dortmund',
    'Lipsia',
    'Berlino',
    'Amburgo',
    'Colonia',
    'Francoforte',
    'Stoccarda',
    'Brema',
    'Hannover',
    'Norimberga',
    'Gelsenkirchen',
    'Leverkusen',
    'Friburgo',
    'Augusta',
    'Mönchengladbach',
    'Bochum',
    'Magonza',
    'Bielefeld',
    'Dresda',
    'Rostock',
    'Essen',
  ],
  featuredClubs: [
    'Monaco Baviera',
    'Dortmund Giallonera',
    'Leverkusen Renania',
    'Lipsia Sassonia',
    'Francoforte Meno',
    'Stoccarda Svevia',
    'Friburgo Brisgovia',
    'Brema Anseatica',
    'Wolfsburg Lupi',
    'Mönchengladbach Puledri',
    'Berlino Ferrea',
    'Amburgo Elba',
    'Colonia Caproni',
    'Hoffenheim Kraichgau',
    'Magonza Carnevale',
    'Augusta Fuggerei',
    'Heidenheim Brenz',
    'Bielefeld Alm',
    'Amburgo Portuale',
    'Rostock Mecleburgo',
  ],
  secondDivisionClubs: [
    'Gelsenkirchen Minatori',
    'Berlino Biancoblù',
    'Hannover Rossa',
    'Kaiserslautern Diavoli',
    'Düsseldorf Renana',
    'Norimberga Franconia',
    'Paderborn Vestfalia',
    'Karlsruhe Baden',
    'Magdeburgo Ottoniana',
    'Darmstadt Assia',
    'Bochum Ruhr',
    'Kiel Baltica',
    'Braunschweig Leoni',
    'Dresda Florentina',
    'Aquisgrana Carolingia',
    'Münster Prussiana',
    'Ratisbona Danubiana',
    'Essen Rossobianca',
    'Saarbrücken Saar',
    'Jena Turingia',
  ],
};

/** Default, fully-validated procedural generation parameters for the MVP. */
export const DEFAULT_WORLD_CONFIG: WorldGenerationConfig = {
  seasonStart: '2024-08-17',
  seasonLengthDays: 300,
  // A real top flight, so a season is a real season: 20 clubs play 38
  // matchdays, home and away, from mid-August to mid-May. At 12 clubs the
  // fixtures were already both legs, but they ran out in January and the
  // calendar looked like half a championship.
  clubsPerTopDivision: 20,
  clubsPerSecondDivision: 20,
  rosterSize: 22,
  age: { min: 16, max: 36, mean: 24, spread: 4 },
  ability: {
    topDivisionMean: 62,
    divisionStep: 12,
    spread: 9,
    min: 20,
    max: 95,
  },
  reputation: { topDivision: 3000, secondDivision: 1200, youth: 400 },
  namePools: {
    IT: italy,
    EN: england,
    ES: spain,
    FR: france,
    DE: germany,
  },
};
